on: 
  workflow_dispatch:
    inputs:
      callbackId:
        description: 'callbackId for correlation with outbound request'
        required: true
      
jobs:
  hello-world:
    runs-on: ubuntu-18.04
    steps:
      - name: display callbackId
        run: echo "callbackId ${{ github.event.inputs.callbackId }} "
