on: workflow_dispatch

jobs:
  hello-world:
    runs-on: ubuntu-18.04
    steps:
      - name: say-hello
        run: echo "hello world!!!!!"
      - name: display callbackId
        run: echo "callbackId ${{ github.event.inputs.home }} "
