name: test-workflow
on: [push]
jobs:
  bootstrap-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm -v
      - run: node -v
