on: 
  workflow_dispatch:
      
jobs:
  success1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - name: s1
        uses: ./actions/delayed
      - name: s2
        uses: ./actions/delayed
        with:
          msg: ${{steps.s1.output.res}}
    outputs:
      res: ${{steps.s2.outputs.res}}
  success2:
    needs: success1
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - name: success2
        uses: ./actions/delayed
        with: 
          shouldFail: false
          msg: ${{needs.success1.outputs.res}}
  failure2:
    needs: success1
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - name: part2
        uses: ./actions/delayed
        with: 
          shouldFail: true
          msg: 'hey'

      
